/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFiadoRouteImport } from './routes/_authenticated/fiado'
import { Route as AuthenticatedLojaRouteImport } from './routes/_authenticated/loja'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedProlaboreRouteImport } from './routes/_authenticated/prolabore'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as LojaPreviewRouteImport } from './routes/loja.preview'
import { Route as VitrineStoreSlugRouteImport } from './routes/vitrine.$storeSlug'
import { Route as AuthenticatedLojaIndexRouteImport } from './routes/_authenticated/loja.index'
import { Route as AuthenticatedLojaClientesRouteImport } from './routes/_authenticated/loja.clientes'
import { Route as AuthenticatedLojaCompartilharRouteImport } from './routes/_authenticated/loja.compartilhar'
import { Route as AuthenticatedLojaConfiguracaoRouteImport } from './routes/_authenticated/loja.configuracao'
import { Route as AuthenticatedLojaCuponsRouteImport } from './routes/_authenticated/loja.cupons'
import { Route as AuthenticatedLojaFreteRouteImport } from './routes/_authenticated/loja.frete'
import { Route as AuthenticatedLojaIntegracoesRouteImport } from './routes/_authenticated/loja.integracoes'
import { Route as AuthenticatedLojaPedidosRouteImport } from './routes/_authenticated/loja.pedidos'
import { Route as AuthenticatedLojaPersonalizarRouteImport } from './routes/_authenticated/loja.personalizar'
import { Route as AuthenticatedLojaProdutosRouteImport } from './routes/_authenticated/loja.produtos'
import { Route as AuthenticatedLojaRelatoriosRouteImport } from './routes/_authenticated/loja.relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFiadoRoute = AuthenticatedFiadoRouteImport.update({
  id: '/fiado',
  path: '/fiado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaRoute = AuthenticatedLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProlaboreRoute = AuthenticatedProlaboreRouteImport.update({
  id: '/prolabore',
  path: '/prolabore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LojaPreviewRoute = LojaPreviewRouteImport.update({
  id: '/loja/preview',
  path: '/loja/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineStoreSlugRoute = VitrineStoreSlugRouteImport.update({
  id: '/vitrine/$storeSlug',
  path: '/vitrine/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLojaIndexRoute = AuthenticatedLojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaClientesRoute =
  AuthenticatedLojaClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaCompartilharRoute =
  AuthenticatedLojaCompartilharRouteImport.update({
    id: '/compartilhar',
    path: '/compartilhar',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaConfiguracaoRoute =
  AuthenticatedLojaConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaCuponsRoute = AuthenticatedLojaCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaFreteRoute = AuthenticatedLojaFreteRouteImport.update({
  id: '/frete',
  path: '/frete',
  getParentRoute: () => AuthenticatedLojaRoute,
} as any)
const AuthenticatedLojaIntegracoesRoute =
  AuthenticatedLojaIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaPedidosRoute =
  AuthenticatedLojaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaPersonalizarRoute =
  AuthenticatedLojaPersonalizarRouteImport.update({
    id: '/personalizar',
    path: '/personalizar',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaProdutosRoute =
  AuthenticatedLojaProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)
const AuthenticatedLojaRelatoriosRoute =
  AuthenticatedLojaRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedLojaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fiado': typeof AuthenticatedFiadoRoute
  '/loja': typeof AuthenticatedLojaRouteWithChildren
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/prolabore': typeof AuthenticatedProlaboreRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/loja/preview': typeof LojaPreviewRoute
  '/vitrine/$storeSlug': typeof VitrineStoreSlugRoute
  '/loja/clientes': typeof AuthenticatedLojaClientesRoute
  '/loja/compartilhar': typeof AuthenticatedLojaCompartilharRoute
  '/loja/configuracao': typeof AuthenticatedLojaConfiguracaoRoute
  '/loja/cupons': typeof AuthenticatedLojaCuponsRoute
  '/loja/frete': typeof AuthenticatedLojaFreteRoute
  '/loja/integracoes': typeof AuthenticatedLojaIntegracoesRoute
  '/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/loja/personalizar': typeof AuthenticatedLojaPersonalizarRoute
  '/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/loja/relatorios': typeof AuthenticatedLojaRelatoriosRoute
  '/loja/': typeof AuthenticatedLojaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fiado': typeof AuthenticatedFiadoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/prolabore': typeof AuthenticatedProlaboreRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/loja/preview': typeof LojaPreviewRoute
  '/vitrine/$storeSlug': typeof VitrineStoreSlugRoute
  '/loja/clientes': typeof AuthenticatedLojaClientesRoute
  '/loja/compartilhar': typeof AuthenticatedLojaCompartilharRoute
  '/loja/configuracao': typeof AuthenticatedLojaConfiguracaoRoute
  '/loja/cupons': typeof AuthenticatedLojaCuponsRoute
  '/loja/frete': typeof AuthenticatedLojaFreteRoute
  '/loja/integracoes': typeof AuthenticatedLojaIntegracoesRoute
  '/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/loja/personalizar': typeof AuthenticatedLojaPersonalizarRoute
  '/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/loja/relatorios': typeof AuthenticatedLojaRelatoriosRoute
  '/loja': typeof AuthenticatedLojaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/fiado': typeof AuthenticatedFiadoRoute
  '/_authenticated/loja': typeof AuthenticatedLojaRouteWithChildren
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/prolabore': typeof AuthenticatedProlaboreRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/loja/preview': typeof LojaPreviewRoute
  '/vitrine/$storeSlug': typeof VitrineStoreSlugRoute
  '/_authenticated/loja/clientes': typeof AuthenticatedLojaClientesRoute
  '/_authenticated/loja/compartilhar': typeof AuthenticatedLojaCompartilharRoute
  '/_authenticated/loja/configuracao': typeof AuthenticatedLojaConfiguracaoRoute
  '/_authenticated/loja/cupons': typeof AuthenticatedLojaCuponsRoute
  '/_authenticated/loja/frete': typeof AuthenticatedLojaFreteRoute
  '/_authenticated/loja/integracoes': typeof AuthenticatedLojaIntegracoesRoute
  '/_authenticated/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/_authenticated/loja/personalizar': typeof AuthenticatedLojaPersonalizarRoute
  '/_authenticated/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/_authenticated/loja/relatorios': typeof AuthenticatedLojaRelatoriosRoute
  '/_authenticated/loja/': typeof AuthenticatedLojaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/fiado'
    | '/loja'
    | '/metas'
    | '/onboarding'
    | '/painel'
    | '/precificacao'
    | '/prolabore'
    | '/relatorio'
    | '/loja/preview'
    | '/vitrine/$storeSlug'
    | '/loja/clientes'
    | '/loja/compartilhar'
    | '/loja/configuracao'
    | '/loja/cupons'
    | '/loja/frete'
    | '/loja/integracoes'
    | '/loja/pedidos'
    | '/loja/personalizar'
    | '/loja/produtos'
    | '/loja/relatorios'
    | '/loja/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/caixa'
    | '/clientes'
    | '/configuracoes'
    | '/estoque'
    | '/fiado'
    | '/metas'
    | '/onboarding'
    | '/painel'
    | '/precificacao'
    | '/prolabore'
    | '/relatorio'
    | '/loja/preview'
    | '/vitrine/$storeSlug'
    | '/loja/clientes'
    | '/loja/compartilhar'
    | '/loja/configuracao'
    | '/loja/cupons'
    | '/loja/frete'
    | '/loja/integracoes'
    | '/loja/pedidos'
    | '/loja/personalizar'
    | '/loja/produtos'
    | '/loja/relatorios'
    | '/loja'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/caixa'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/estoque'
    | '/_authenticated/fiado'
    | '/_authenticated/loja'
    | '/_authenticated/metas'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/_authenticated/precificacao'
    | '/_authenticated/prolabore'
    | '/_authenticated/relatorio'
    | '/loja/preview'
    | '/vitrine/$storeSlug'
    | '/_authenticated/loja/clientes'
    | '/_authenticated/loja/compartilhar'
    | '/_authenticated/loja/configuracao'
    | '/_authenticated/loja/cupons'
    | '/_authenticated/loja/frete'
    | '/_authenticated/loja/integracoes'
    | '/_authenticated/loja/pedidos'
    | '/_authenticated/loja/personalizar'
    | '/_authenticated/loja/produtos'
    | '/_authenticated/loja/relatorios'
    | '/_authenticated/loja/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LojaPreviewRoute: typeof LojaPreviewRoute
  VitrineStoreSlugRoute: typeof VitrineStoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiado': {
      id: '/_authenticated/fiado'
      path: '/fiado'
      fullPath: '/fiado'
      preLoaderRoute: typeof AuthenticatedFiadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prolabore': {
      id: '/_authenticated/prolabore'
      path: '/prolabore'
      fullPath: '/prolabore'
      preLoaderRoute: typeof AuthenticatedProlaboreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/loja/preview': {
      id: '/loja/preview'
      path: '/loja/preview'
      fullPath: '/loja/preview'
      preLoaderRoute: typeof LojaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine/$storeSlug': {
      id: '/vitrine/$storeSlug'
      path: '/vitrine/$storeSlug'
      fullPath: '/vitrine/$storeSlug'
      preLoaderRoute: typeof VitrineStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loja/': {
      id: '/_authenticated/loja/'
      path: '/'
      fullPath: '/loja/'
      preLoaderRoute: typeof AuthenticatedLojaIndexRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/clientes': {
      id: '/_authenticated/loja/clientes'
      path: '/clientes'
      fullPath: '/loja/clientes'
      preLoaderRoute: typeof AuthenticatedLojaClientesRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/compartilhar': {
      id: '/_authenticated/loja/compartilhar'
      path: '/compartilhar'
      fullPath: '/loja/compartilhar'
      preLoaderRoute: typeof AuthenticatedLojaCompartilharRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/configuracao': {
      id: '/_authenticated/loja/configuracao'
      path: '/configuracao'
      fullPath: '/loja/configuracao'
      preLoaderRoute: typeof AuthenticatedLojaConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/cupons': {
      id: '/_authenticated/loja/cupons'
      path: '/cupons'
      fullPath: '/loja/cupons'
      preLoaderRoute: typeof AuthenticatedLojaCuponsRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/frete': {
      id: '/_authenticated/loja/frete'
      path: '/frete'
      fullPath: '/loja/frete'
      preLoaderRoute: typeof AuthenticatedLojaFreteRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/integracoes': {
      id: '/_authenticated/loja/integracoes'
      path: '/integracoes'
      fullPath: '/loja/integracoes'
      preLoaderRoute: typeof AuthenticatedLojaIntegracoesRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/pedidos': {
      id: '/_authenticated/loja/pedidos'
      path: '/pedidos'
      fullPath: '/loja/pedidos'
      preLoaderRoute: typeof AuthenticatedLojaPedidosRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/personalizar': {
      id: '/_authenticated/loja/personalizar'
      path: '/personalizar'
      fullPath: '/loja/personalizar'
      preLoaderRoute: typeof AuthenticatedLojaPersonalizarRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/produtos': {
      id: '/_authenticated/loja/produtos'
      path: '/produtos'
      fullPath: '/loja/produtos'
      preLoaderRoute: typeof AuthenticatedLojaProdutosRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
    '/_authenticated/loja/relatorios': {
      id: '/_authenticated/loja/relatorios'
      path: '/relatorios'
      fullPath: '/loja/relatorios'
      preLoaderRoute: typeof AuthenticatedLojaRelatoriosRouteImport
      parentRoute: typeof AuthenticatedLojaRoute
    }
  }
}

interface AuthenticatedLojaRouteChildren {
  AuthenticatedLojaClientesRoute: typeof AuthenticatedLojaClientesRoute
  AuthenticatedLojaCompartilharRoute: typeof AuthenticatedLojaCompartilharRoute
  AuthenticatedLojaConfiguracaoRoute: typeof AuthenticatedLojaConfiguracaoRoute
  AuthenticatedLojaCuponsRoute: typeof AuthenticatedLojaCuponsRoute
  AuthenticatedLojaFreteRoute: typeof AuthenticatedLojaFreteRoute
  AuthenticatedLojaIntegracoesRoute: typeof AuthenticatedLojaIntegracoesRoute
  AuthenticatedLojaPedidosRoute: typeof AuthenticatedLojaPedidosRoute
  AuthenticatedLojaPersonalizarRoute: typeof AuthenticatedLojaPersonalizarRoute
  AuthenticatedLojaProdutosRoute: typeof AuthenticatedLojaProdutosRoute
  AuthenticatedLojaRelatoriosRoute: typeof AuthenticatedLojaRelatoriosRoute
  AuthenticatedLojaIndexRoute: typeof AuthenticatedLojaIndexRoute
}

const AuthenticatedLojaRouteChildren: AuthenticatedLojaRouteChildren = {
  AuthenticatedLojaClientesRoute: AuthenticatedLojaClientesRoute,
  AuthenticatedLojaCompartilharRoute: AuthenticatedLojaCompartilharRoute,
  AuthenticatedLojaConfiguracaoRoute: AuthenticatedLojaConfiguracaoRoute,
  AuthenticatedLojaCuponsRoute: AuthenticatedLojaCuponsRoute,
  AuthenticatedLojaFreteRoute: AuthenticatedLojaFreteRoute,
  AuthenticatedLojaIntegracoesRoute: AuthenticatedLojaIntegracoesRoute,
  AuthenticatedLojaPedidosRoute: AuthenticatedLojaPedidosRoute,
  AuthenticatedLojaPersonalizarRoute: AuthenticatedLojaPersonalizarRoute,
  AuthenticatedLojaProdutosRoute: AuthenticatedLojaProdutosRoute,
  AuthenticatedLojaRelatoriosRoute: AuthenticatedLojaRelatoriosRoute,
  AuthenticatedLojaIndexRoute: AuthenticatedLojaIndexRoute,
}

const AuthenticatedLojaRouteWithChildren =
  AuthenticatedLojaRoute._addFileChildren(AuthenticatedLojaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFiadoRoute: typeof AuthenticatedFiadoRoute
  AuthenticatedLojaRoute: typeof AuthenticatedLojaRouteWithChildren
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedProlaboreRoute: typeof AuthenticatedProlaboreRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFiadoRoute: AuthenticatedFiadoRoute,
  AuthenticatedLojaRoute: AuthenticatedLojaRouteWithChildren,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedProlaboreRoute: AuthenticatedProlaboreRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LojaPreviewRoute: LojaPreviewRoute,
  VitrineStoreSlugRoute: VitrineStoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
